# Generated by Django 5.2.4 on 2025-07-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='description',
            field=models.CharField(default='No description available', max_length=50),
        ),
    ]
